### ISSUE TITLE
Map story about Pou3f2 to needed datasets

### ISSUE THREAD

**Issue by RLC-DCPPC** [RLC-DCPPC/NeMO-Analytics#2]
Top-level issue to contain sub-tasks:

- [ ] in vivo cortex development bulk RNA-seq (#8) 
- [ ] in vivo cortex development single-cell RNA-seq (#9)
- [ ] stem cell models of human cortex development (bulk RNA-seq/microarrays) (#10)
- [ ] stem cell models of human cortex development single-cell RNA-seq (#11)
- [ ] in vivo epigenomics data (#12)

**Comment by seth-ament** [comment]
1. in vivo cortex development bulk RNA-seq
1a. BrainSpan DLPFC bulk RNA-seq
1b. LIBD BrainSeq DLPFC data
1c. non-human primate laser microdissection (gene expression microarrays)

2. in vivo cortex development single-cell RNA-seq
2a. Kriegstein "6k" human cortex development single-cell RNA-seq (SMART-seq)
2b. Darmanis/Quake human cortex development single-cell RNA-seq (SMART-seq)
2c. Kriegstein 10x human DLPFC development single-cell RNA-seq (10x)

3. stem cell models of human cortex development (bulk RNA-seq/microarrays)
3a. CORTECON
3b. POU3F2 over-expression in neural progenitors (Pearl et al. in press)

4. stem cell models of human cortex development single-cell RNA-seq
[several datasets in this space -- maybe choose 1-2]
4a. Vaccarino PsychENCODE 2018 organoids
4b. ...

5. in vivo epigenomics data
5a. human DLPFC ATAC-seq CP vs. VZ (Geschwind Cell 2018; ATAC-seq)
5b. ROADMAP fetal brain chromatin states

**Comment by RLC-DCPPC** [comment]
Bob to create issues. In priority order.

**Comment by RLC-DCPPC** [comment]
Seth to think about SVG-type visualizations where appropriate.

**Comment by RLC-DCPPC** [comment]
Created sub-tasks as linked through the to-do list in the description.

**Comment by RLC-DCPPC** [comment]
Kamino cloned this issue to [nemoarchive/analytics](https://github.com/nemoarchive/analytics/issues/4)
